services:
  app:
    container_name: ana-data
    image: ${IMAGE:-ghcr.io/bolinocroustibat/artificial-non-intelligence-data:latest}
    build:
      context: .
    ports:
      - "${APP_PORT:-8501}:8501"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-unknown}
      # host.docker.internal is a special DNS name that resolves to the host machine's IP address
      # This allows the container to access services running on the host (like PostgreSQL) in both development and production
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - SENTRY_DSN=${SENTRY_DSN}
    volumes:
      - .:/app
    restart: unless-stopped
    # Add extra hosts to resolve host.docker.internal on Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
