name: Deploy to prod when tag

on:
  push:
    tags:
      - '*'

jobs:
  bump-version:
    name: Bump version to ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Bump version in pyproject.toml and uv.lock to ${{ github.ref_name }}
        run: |
          sed -i 's/^version = .*/version = "${{ github.ref_name }}"/' pyproject.toml
          uv lock

      - name: Commit and push updated pyproject.toml and uv.lock
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "chore: bump version to ${{ github.ref_name }}"
          commit_user_name: Adrien Carpentier
          commit_user_email: me@adriencarpentier.com
          commit_author: Adrien Carpentier <me@adriencarpentier.com>

  deploy:
    name: Deploy ${{ github.ref_name }} to prod
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump-version.outputs.commit_hash }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.SSH_HOST }}

      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy repository to server with rsync
        run: rsync -avz --exclude '.git' --chown=github:www-data --chmod=Dg=rwx,Fg=rwx ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/www/artificial-non-intelligence-data/

      - name: Execute server commands for deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/www/artificial-non-intelligence-data
            /usr/local/bin/uv sync
            sudo systemctl restart ani-data.service

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: "adrien-carpentier"
          SENTRY_PROJECT: "artificial-non-intelligence-data"
        with:
          environment: production
          release: ${{ github.ref_name }}
