name: Deploy to prod when tag

on:
  push:
    tags:
      - '*'

jobs:
  deploy-prod:
    name: Deploy ${{ github.ref_name }} to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.SSH_HOST }}

      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy repository to server with rsync
        run: rsync -avz --exclude '.git' --chown=github:www-data --chmod=Dg=rwx,Fg=rwx ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/www/artificial-non-intelligence-data/ # We set directory (D) and files (F) permission for group www-data to rwx so that the same users can overwrite later

      - name: Execute server commands for deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/www/artificial-non-intelligence-data
            source /home/www/artificial-non-intelligence-data/.venv/bin/activate
            pip install -r /home/www/artificial-non-intelligence-data/requirements.lock
            sudo systemctl restart ani-data.service

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: "adrien-carpentier"
          SENTRY_PROJECT: "artificial-non-intelligence-data"
        with:
          environment: production
          version: ${{ github.ref_name }}
